const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const API_BASE=(window.SHOBHIT_API_BASE||'').replace(/\/$/,'');
document.addEventListener('DOMContentLoaded',()=>{
 const toggle=$('#menuToggle'),links=$('#navLinks');if(toggle&&links)toggle.onclick=()=>{links.classList.toggle('open');toggle.setAttribute('aria-expanded',String(links.classList.contains('open')))};
 const current=location.pathname.split('/').pop()||'index.html';$$('.nav-links a').forEach(a=>{if(a.getAttribute('href')===current||(current==='index.html'&&a.getAttribute('href')==='/'))a.classList.add('active')});const year=$('#year');if(year)year.textContent=new Date().getFullYear();
 async function api(url,body){const r=await fetch(API_BASE+url,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'Something went wrong.');return d}
 function msg(el,text,ok=false){if(el){el.textContent=text;el.className='message '+(ok?'success':'error')}}
 const join=$('#joinForm');if(join)join.onsubmit=async e=>{e.preventDefault();const b=join.querySelector('button'),m=$('#formMessage');b.disabled=true;b.textContent='Creating account…';try{await api('/api/auth/join',Object.fromEntries(new FormData(join)));msg(m,'Account created! Opening dashboard…',true);setTimeout(()=>location.href='/dashboard.html',400)}catch(x){msg(m,x.message)}finally{b.disabled=false;b.textContent='Create account'}};
 const login=$('#loginForm');if(login)login.onsubmit=async e=>{e.preventDefault();const b=login.querySelector('button'),m=$('#formMessage');b.disabled=true;b.textContent='Signing in…';try{await api('/api/auth/login',Object.fromEntries(new FormData(login)));msg(m,'Welcome back! Opening dashboard…',true);setTimeout(()=>location.href='/dashboard.html',350)}catch(x){msg(m,x.message)}finally{b.disabled=false;b.textContent='Log in'}};
 const dash=$('#dashboardRoot');if(dash){fetch(API_BASE+'/api/auth/me',{credentials:'include'}).then(async r=>{if(!r.ok)throw Error();return r.json()}).then(({user:u})=>{$('#welcomeName').textContent=u.name;$('#profileName').textContent=u.name;$('#profileEmail').textContent=u.email;$('#memberSince').textContent=new Date(u.createdAt).toLocaleDateString(undefined,{month:'short',year:'numeric'})}).catch(()=>{const m=$('#dashboardMessage');if(m){msg(m,'Please log in to view your dashboard.')}else location.replace('/login.html')});const out=$('#logoutButton');if(out)out.onclick=async()=>{try{await api('/api/auth/logout',{})}catch{}location.href='/'}}
 const contact=$('#contactForm');if(contact)contact.onsubmit=async e=>{e.preventDefault();const b=contact.querySelector('button'),m=$('#formMessage');b.disabled=true;b.textContent='Checking…';try{const d=await api('/api/contact',Object.fromEntries(new FormData(contact)));msg(m,d.message,true);contact.reset()}catch(x){msg(m,x.message)}finally{b.disabled=false;b.textContent='Send message'}};
});
